version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    stdin_open: true 
    tty: true
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - api:/usr/src/app

  db:
    image: postgres:16.4-alpine3.20
    container_name: ${DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: bank
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d bank"]
      interval: 2s
      retries: 5
      start_period: 10s
      timeout: 2s

volumes:
  pgdata:
  api: